# Generated by Django 4.1.4 on 2022-12-28 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='car', max_length=50, verbose_name='Title')),
                ('price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('color', models.CharField(max_length=20)),
                ('image', models.ImageField(upload_to='photos/%y/%m/%d')),
                ('description', models.TextField(blank=True, null=True)),
                ('model', models.CharField(choices=[('2013', '2013'), ('2014', '2014'), ('2015', '2015')], default='default', max_length=50)),
            ],
        ),
    ]
