# Generated by Django 4.1.4 on 2023-01-11 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(default='Donation', max_length=50, verbose_name='Title')),
                ('Targetprice', models.DecimalField(decimal_places=2, max_digits=7)),
                ('image', models.ImageField(upload_to='media/%y/%m/%d')),
                ('Description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Car',
        ),
    ]
