# Generated by Django 4.1.4 on 2023-01-22 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_donation_delete_car'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='Description',
            field=models.TextField(blank=True, null=True, verbose_name='Description     '),
        ),
        migrations.AlterField(
            model_name='donation',
            name='Name',
            field=models.CharField(default='Donation', max_length=50, verbose_name='Name     '),
        ),
        migrations.AlterField(
            model_name='donation',
            name='Targetprice',
            field=models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Price    '),
        ),
        migrations.AlterField(
            model_name='donation',
            name='image',
            field=models.ImageField(upload_to='media/%y/%m/%d', verbose_name='Image     '),
        ),
    ]
