# Generated by Django 4.1.4 on 2023-01-22 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_alter_donation_description_alter_donation_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Funded',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
            ],
        ),
    ]
